name: NeutroTrack

channels:
  - conda-forge
  - anaconda
      
dependencies:
  - python=3.9
  - pyqt=5.12.3
  - napari[all]=0.4.16
  - numpy=1.23.2
  - pandas=1.4.3
  - scipy=1.9.1
  - scikit-image=0.19.3
  - scikit-learn
  - matplotlib-base=3.5.3
  - joblib=1.1.0
  - pip=22.2.2
  - pip:
    - opencv-python
    - patchify
